version: '2'
services:
  wg:
    image: linuxserver/wireguard
    container_name: wg
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.10.10.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    ports:
      - 51820:51820/udp
      - 51820:51820/tcp
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1